/* Generated by the Nim Compiler v1.5.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

// ==UserScript==
// @name Userscript example\nconsole.log('test')
// @name:pt-br Exemplo de userscript
// @namespace Violentmonkey Scripts
// @description A simple example to test the GM bindings in Nim
// @description:pt-br Um simples exemplo para testar os bindings do GM no Nim
// @version 0.1.0
// @author Thisago
// @icon https://gitea.com/avatars/be2da4e8a9cbffdc433db9058105a1ce?size=112
// @resource customCss http://127.0.0.1/u3/apache/www/libs/button/button.css
// @supportURL http://localhost/support
// @homepageURL http://localhost/home
// @match *://localhost/*
// @match *://127.0.0.1/*
// @exclude-match *://duckduckgo/*
// @exclude-match *://bing/
// @include *://localhost/*
// @include *://localhost/
// @exclude *://google/*
// @exclude *://bing/
// @grant GM.info
// @run-at document-start
// @downloadURL file:///data/os/dev/nim/lib/gm_api/example/main.js
// ==/UserScript==
// Metadata automatically generated
console.log("// ==UserScript==\n// @name Userscript example\\nconsole.log('test')\n// @name:pt-br Exemplo de userscript\n// @namespace Violentmonkey Scripts\n// @description A simple example to test the GM bindings in Nim\n// @description:pt-br Um simples exemplo para testar os bindings do GM no Nim\n// @version 0.1.0\n// @author Thisago\n// @icon https://gitea.com/avatars/be2da4e8a9cbffdc433db9058105a1ce?size=112\n// @resource customCss http://127.0.0.1/u3/apache/www/libs/button/button.css\n// @supportURL http://localhost/support\n// @homepageURL http://localhost/home\n// @match *://localhost/*\n// @match *://127.0.0.1/*\n// @exclude-match *://duckduckgo/*\n// @exclude-match *://bing/\n// @include *://localhost/*\n// @include *://localhost/\n// @exclude *://google/*\n// @exclude *://bing/\n// @grant GM.info\n// @run-at document-start\n// @downloadURL file:///data/os/dev/nim/lib/gm_api/example/main.js\n// ==/UserScript==\n// Metadata automatically generated");
console.log(GM.info());
